name: TFB-Walls
main: uk.co.thefailboat.TFBWalls.Main
version: 0.2-DEV
author: TFB

commands:
   TimerTest:
         description: Test the timer
         permission: tfbwalls.timer.test
         usage: /timer-test
   kickall:
         description: Kick all players with an optional reason
         permission: tfbwalls.kick.kickall
         usage: /kickall {reason}
   kick:
         description: Kick a player with an optional reason
         permission: tfbwalls.kick.kick
         usage: /kick [Player] {reason}
   Getpos:
         description: Get the current position of the player and output to console (Debug)
         permission: tfbwalls.getpos
         usage: /getpos
   ToggleFreeze:
         description: Toggle the freeze state of the current player, or yourself.
         permission: tfbwalls.togglefreeze
         usage: /togglefreeze {Player}