name: TFB-Walls
main: uk.co.thefailboat.TFBWalls.TFBWalls
version: 0.1-DEV
author: TFB

commands:
   TimerTest:
         description: Test the timer
         permission: tfbwalls.timer.test
         usage: /timer-test
   kickall:
         description: Kick all players with an optional reason
         permission: tfbwalls.kick.kickall
         usage: /kickall {reason}
   kick:
         description: Kick a player with an optional reason
         permission: tfbwalls.kick.kick
         usage: /kick [Player] {reason}